{%- import 'macros' as macros with context -%}
---
name: "Build"

on:
  workflow_call:

defaults:
  run:
    working-directory: "pulp-cli{{ cookiecutter.__app_label_suffix }}"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout() | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      - name: "Build wheels"
        run: |
          make build
          touch .root
      - name: "Upload wheels"
        uses: "actions/upload-artifact@v6"
        with:
          name: "pulp_cli_packages"
          path: |
            pulp-cli{{ cookiecutter.__app_label_suffix }}/.root
            pulp-cli{{ cookiecutter.__app_label_suffix }}/dist/
          if-no-files-found: "error"
          retention-days: 5
...
