{%- import 'macros' as macros with context -%}
---
name: "Collect changes"
on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: "pulp-cli{{ cookiecutter.__app_label_suffix }}"

jobs:
  collect-changes:
    permissions:
      contents: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout(deep=true) | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      {{ macros.setup_git() | indent(6) }}
      - name: "Collect changes"
        run: |
          uv run --script .ci/scripts/collect_changes.py
      {{ macros.create_pr("update_changes", "Update Changelog") | indent(6) }}
...
