{%- import 'macros' as macros with context -%}
---
name: "Update CI from cookiecutter"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 {{ cookiecutter.app_label | hour }} * * 0"

defaults:
  run:
    working-directory: "pulp-cli{{ cookiecutter.__app_label_suffix }}"

jobs:
  update-ci:
    permissions:
      contents: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          repository: "pulp/pulp-cli"
          path: "pulp-cli"
      {{ macros.checkout() | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      {{ macros.setup_git() | indent(6) }}
      - name: "Apply cookiecutter templates"
        run: |
          uv run ../pulp-cli/cookiecutter/apply_templates.py
          if [ "$(git status --porcelain)" ]
          then
            git add .
            git commit -m "Update cookiecutter"
          fi
      {{ macros.create_pr("update_cookiecutter", "Update cookiecutter") | indent(6) }}
  {%- if cookiecutter.app_label %}
  update-dependencies:
    permissions:
      contents: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          repository: "pulp/pulp-cli"
          path: "pulp-cli"
      - uses: "actions/checkout@v6"
        with:
          path: "pulp-cli{{ cookiecutter.__app_label_suffix }}"
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      {{ macros.setup_git() | indent(6) }}
      - name: "Apply cookiecutter templates"
        run: |
          uv run ../pulp-cli/cookiecutter/update_pulp_cli.py
          if [ "$(git status --porcelain)" ]
          then
            git add .
            git commit -m "Update CLI and GLUE"
          fi
      {{ macros.create_pr("update_cli", "Update CLI and GLUE") | indent(6) }}
    {%- endif %}
...
