{%- import 'macros' as macros with context -%}
---
name: "pulp-cli Publish"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: "./.github/workflows/build.yml"
  publish-pypi:
    name: "Publish to PyPI"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout() | indent(6) }}
      {{ macros.download_wheels() | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      - name: "Publish"
        env:
          {%- raw %}
          UV_PUBLISH_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
          {%- endraw %}
        run: |
          uv publish
...
