{%- import 'macros' as macros with context -%}
---
name: "pulp-cli Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          {%- raw %}
          token: "${{ secrets.RELEASE_TOKEN }}"
          {%- endraw %}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      {{ macros.setup_git() | indent(6) }}
      - name: "Release"
        run: |
          uv run --with bump-my-version~=0.20.0 --with towncrier~=23.11.0 .ci/scripts/release.sh
...
