{%- import 'macros' as macros with context -%}
---
name: "Create Release Branch"
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: "pulp-cli{{ cookiecutter.__app_label_suffix }}"

jobs:
  create-release-branch:
    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout() | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      {{ macros.setup_git() | indent(6) }}
      - name: "Create Release Branch"
        run: |
          uv run --with bump-my-version~=0.20.0 .ci/scripts/create_release_branch.sh
      {{ macros.create_pr("bump_version", "Bump dev-version") | indent(6) }}
      - name: "Add Backport Label for new Branch"
        uses: "actions/github-script@v8"
        with:
          script: |
            const { NEW_BRANCH } = process.env;
            const labelName = "backport-" + NEW_BRANCH;

            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: labelName,
              color: "C8780A",
            });
...
