{%- import 'macros' as macros with context -%}
---
name: "Tag Release"

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: "pulp-cli{{ cookiecutter.__app_label_suffix }}"

jobs:
  release:
    name: "Release"
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
      {{ macros.checkout() | indent(6) }}
      {{ macros.setup_python() | indent(6) }}
      {{ macros.install_uv() | indent(6) }}
      {{ macros.setup_git() | indent(6) }}
      - name: "Release"
        run: |
          uv run --with bump-my-version~=0.20.0 --with towncrier~=23.11.0 .ci/scripts/release.sh
...
