name: "pulp-cli Publish"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: "./.github/workflows/build.yml"
  publish-pypi:
    name: "Publish to PyPI"
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Download wheels"
        uses: "actions/download-artifact@v4"
        with:
          name: "pulp_cli_packages"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: "Build and publish"
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "{{ "${{ secrets.PYPI_API_TOKEN }}" }}"
        run: |
          cd pulp-glue{{ cookiecutter.__app_label_suffix }}
          twine upload dist/*
          cd ..
          twine upload dist/*
{%- if cookiecutter.docs %}
  publish-docs:
    needs:
      - "publish-pypi"
    uses: "./.github/workflows/publish_docs.yml"
    secrets: "inherit"
{%- endif %}
