name: "pulp-cli Publish Docs"

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "doc_requirements.txt"
  workflow_dispatch:
  workflow_call:

jobs:
  publish-docs:
    name: "Publish docs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Run publish docs script"
        env:
          PULP_DOCS_KEY: "${{ secrets.PULP_DOCS_KEY }}"
        run: |
          pip install -r doc_requirements.txt
          .ci/scripts/publish_docs.sh "${GITHUB_REF}"
