name: "Docs"

on:
  workflow_call:

jobs:
  test:
    if: "endsWith(github.base_ref, 'main')"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/*constraints.lock', '**/setup.py', '**/pyproject.toml') }}"
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Install Test Dependencies"
        run: |
          pip install -r doc_requirements.txt
      - name: "Build docs"
        run: |
          make docs
  no-test:
    if: "!endsWith(github.base_ref, 'main')"
    runs-on: "ubuntu-20.04"
    steps:
      - run: |
          echo "Skip docs testing on non-main branches."
