---
name: Create Release Branch
on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup git
        run: |
          git config user.name pulpbot
          git config user.email pulp-infra@redhat.com
      - name: Install python dependencies
        run: pip install bump2version
      - name: Create Release Branch
        run: .ci/scripts/create_release_branch.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          title: "Bump dev-version"
          body: ""
          branch: "bump_version"
          delete-branch: true
