---
name: "pulp-cli Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.14"
          allow-prereleases: true
      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
        with:
          enable-cache: true
      - name: "Setup git"
        run: |
          git config user.name pulpbot
          git config user.email pulp-infra@redhat.com
      - name: "Release"
        run: |
          uv run --with bump-my-version~=0.20.0 --with towncrier~=23.11.0 .ci/scripts/release.sh
...
